import { sql, type Kysely } from 'kysely';
import type { DatabaseSchema } from '../index.js';
export async function up(db: Kysely<DatabaseSchema>): Promise<void> {
  await sql`
    create schema if not exists reviews;
    create table reviews.review_access_tokens (id uuid primary key default uuidv7(),organization_id uuid not null references platform.organizations(id),customer_id uuid not null references customers.customers(id),order_line_id uuid not null references orders.order_lines(id),product_id uuid not null references catalog.products(id),token_hash text not null unique,expires_at timestamptz null,revoked_at timestamptz null,used_at timestamptz null,created_at timestamptz not null default now(),unique(organization_id,id));
    create table reviews.reviews (id uuid primary key default uuidv7(),organization_id uuid not null references platform.organizations(id),product_id uuid not null references catalog.products(id),customer_id uuid not null references customers.customers(id),verification_order_line_id uuid null references orders.order_lines(id),source text not null default 'CUSTOMER' check(source in ('CUSTOMER','MIGRATION','CONTROLLED_IMPORT')),lifecycle_status text not null default 'ACTIVE' check(lifecycle_status in ('ACTIVE','REMOVED')),visibility_status text not null default 'HIDDEN' check(visibility_status in ('VISIBLE','HIDDEN')),published_revision_id uuid null,withdrawn_at timestamptz null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version bigint not null default 1,unique(organization_id,id));
    create table reviews.review_revisions (id uuid primary key default uuidv7(),organization_id uuid not null references platform.organizations(id),review_id uuid not null references reviews.reviews(id),revision_number integer not null,rating integer not null check(rating between 1 and 5),title text null check(title is null or length(title)<=160),body text null check(body is null or length(body)<=5000),public_display_name text not null,moderation_status text not null default 'PENDING' check(moderation_status in ('PENDING','APPROVED','REJECTED')),submitted_at timestamptz not null default now(),moderated_at timestamptz null,moderated_by uuid null references iam.users(id),moderation_reason text null check(moderation_reason is null or moderation_reason in ('SPAM','DUPLICATE','IRRELEVANT','ABUSIVE_OR_THREATENING','PERSONAL_INFORMATION','UNSAFE_MEDIA','FRAUD_SUSPECTED','PROHIBITED_CONTENT','OTHER')),internal_note text null,created_at timestamptz not null default now(),unique(review_id,revision_number),unique(organization_id,id),foreign key(organization_id,review_id) references reviews.reviews(organization_id,id));
    alter table reviews.reviews add constraint reviews_published_revision_fk foreign key(published_revision_id) references reviews.review_revisions(id);
    create table reviews.review_media (id uuid primary key default uuidv7(),organization_id uuid not null references platform.organizations(id),review_revision_id uuid not null references reviews.review_revisions(id),media_asset_id uuid not null references media.media_assets(id),position integer not null default 0,created_at timestamptz not null default now(),unique(review_revision_id,media_asset_id),unique(organization_id,id),foreign key(organization_id,review_revision_id) references reviews.review_revisions(organization_id,id));
    create table reviews.merchant_responses (id uuid primary key default uuidv7(),organization_id uuid not null references platform.organizations(id),review_id uuid not null references reviews.reviews(id),body text not null check(length(body)<=3000),status text not null default 'VISIBLE' check(status in ('VISIBLE','HIDDEN')),created_by uuid not null references iam.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version bigint not null default 1,unique(review_id),unique(organization_id,id),foreign key(organization_id,review_id) references reviews.reviews(organization_id,id));
    create table reviews.product_rating_summary (organization_id uuid not null references platform.organizations(id),product_id uuid not null references catalog.products(id),rating_count integer not null default 0,rating_sum integer not null default 0,rating_1_count integer not null default 0,rating_2_count integer not null default 0,rating_3_count integer not null default 0,rating_4_count integer not null default 0,rating_5_count integer not null default 0,text_review_count integer not null default 0,media_review_count integer not null default 0,updated_at timestamptz not null default now(),primary key(organization_id,product_id),check(rating_count=rating_1_count+rating_2_count+rating_3_count+rating_4_count+rating_5_count));
    create index reviews_product_public on reviews.reviews(organization_id,product_id,created_at desc) where lifecycle_status='ACTIVE' and visibility_status='VISIBLE';
    create index review_revisions_review on reviews.review_revisions(review_id,revision_number desc); create index review_access_token_scope on reviews.review_access_tokens(organization_id,product_id,customer_id);
    insert into iam.capability_definitions(capability_code,domain,description,sensitivity) values ('reviews.view','reviews','View review moderation data.','INTERNAL'),('reviews.moderate','reviews','Approve, reject, hide, or restore reviews.','HIGH'),('reviews.respond','reviews','Publish merchant review responses.','HIGH'),('reviews.integrity','reviews','Rebuild review rating projections.','HIGH') on conflict(capability_code) do nothing;
    insert into iam.membership_capability_grants(membership_id,capability_code) select m.id,c.capability_code from iam.organization_memberships m cross join (values('reviews.view'),('reviews.moderate'),('reviews.respond'),('reviews.integrity')) c(capability_code) where m.membership_type='OWNER' and m.status='ACTIVE' on conflict do nothing;
  `.execute(db);
}
export async function down(): Promise<void> {
  throw new Error('Review history is append-only.');
}
